"""alertas: estandar como fraccion, tabla de alertas

Revision ID: 4d068c07174f
Revises: b78cd40ec39c
Create Date: 2026-08-29 17:08:00.851022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d068c07174f'
down_revision: Union[str, Sequence[str], None] = 'b78cd40ec39c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('estandares', 'mortandad_acumulada_esperada',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=7, scale=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('estandares', 'mortandad_acumulada_esperada',
               existing_type=sa.Numeric(precision=7, scale=5),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
