"""modelo inicial

Revision ID: 6b6b99141ff5
Revises: 
Create Date: 2026-08-26 16:32:54.283430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6b99141ff5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estandares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_de_crianza', sa.Integer(), nullable=False),
    sa.Column('mortandad_max_esperada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('consumo_agua_esperado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('consumo_alimento_esperado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('peso_esperado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('galpones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tabla_liquidacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indice_conversion_min', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('indice_conversion_max', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('indice_crecimiento_min', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('indice_crecimiento_max', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('precio_por_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'granjero', name='rolusuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('crianzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('en_curso', 'cerrada', name='estadocrianza'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cierres_crianza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crianza_id', sa.Integer(), nullable=False),
    sa.Column('total_aves_entregadas', sa.Integer(), nullable=False),
    sa.Column('peso_total_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('indice_crecimiento', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('indice_conversion', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('precio_por_kg_resultante', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['crianza_id'], ['crianzas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crianza_id')
    )
    op.create_table('crianza_galpones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crianza_id', sa.Integer(), nullable=False),
    sa.Column('galpon_id', sa.Integer(), nullable=False),
    sa.Column('granjero_id', sa.Integer(), nullable=False),
    sa.Column('aves_iniciales', sa.Integer(), nullable=False),
    sa.Column('peso_inicial_promedio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['crianza_id'], ['crianzas.id'], ),
    sa.ForeignKeyConstraint(['galpon_id'], ['galpones.id'], ),
    sa.ForeignKeyConstraint(['granjero_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_diarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crianza_galpon_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('dia_de_crianza', sa.Integer(), nullable=False),
    sa.Column('mortandad', sa.Integer(), nullable=False),
    sa.Column('consumo_agua', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('consumo_alimento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('consumo_gas', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('consumo_electricidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('peso_promedio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cargado_por_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cargado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['crianza_galpon_id'], ['crianza_galpones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_diario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('mortandad', 'agua', 'alimento', 'peso', name='tipoalerta'), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resuelta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['registro_diario_id'], ['registros_diarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertas')
    op.drop_table('registros_diarios')
    op.drop_table('crianza_galpones')
    op.drop_table('cierres_crianza')
    op.drop_table('crianzas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('tabla_liquidacion')
    op.drop_table('galpones')
    op.drop_table('estandares')
    # ### end Alembic commands ###
