"""modelo real: galpon vs granja, ingresos, entregas, retiro, cierre

Revision ID: b78cd40ec39c
Revises: 
Create Date: 2026-08-27 00:34:39.218625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78cd40ec39c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estandares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_vida', sa.Integer(), nullable=False),
    sa.Column('mortandad_acumulada_esperada', sa.Integer(), nullable=False),
    sa.Column('agua_litros_pollo_esperado', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estandares_dia_vida'), 'estandares', ['dia_vida'], unique=True)
    op.create_table('galpones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'granjero', name='rolusuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('crianzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('en_curso', 'cerrada', name='estadocrianza'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crianzas_numero'), 'crianzas', ['numero'], unique=True)
    op.create_table('cierres_crianza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crianza_id', sa.Integer(), nullable=False),
    sa.Column('total_aves_entregadas', sa.Integer(), nullable=False),
    sa.Column('peso_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ie_promedio', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('indice_tabla', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('premios', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gas_ajuste', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ajuste', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_x_pollo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['crianza_id'], ['crianzas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crianza_id')
    )
    op.create_table('crianza_galpones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crianza_id', sa.Integer(), nullable=False),
    sa.Column('galpon_id', sa.Integer(), nullable=False),
    sa.Column('granjero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crianza_id'], ['crianzas.id'], ),
    sa.ForeignKeyConstraint(['galpon_id'], ['galpones.id'], ),
    sa.ForeignKeyConstraint(['granjero_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entregas_insumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crianza_id', sa.Integer(), nullable=False),
    sa.Column('tipo_insumo', sa.Enum('alimento', 'cascara', name='tipoinsumo'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('remito', sa.String(length=50), nullable=False),
    sa.Column('tipo_alimento', sa.Integer(), nullable=True),
    sa.Column('kilos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cargado_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cargado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['crianza_id'], ['crianzas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecturas_diarias_granja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crianza_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_desde', sa.Time(), nullable=False),
    sa.Column('hora_hasta', sa.Time(), nullable=False),
    sa.Column('lectura_gas', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lectura_electricidad_activa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lectura_electricidad_reactiva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cargado_por_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cargado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['crianza_id'], ['crianzas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crianza_id', 'fecha')
    )
    op.create_table('cierres_galpon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crianza_galpon_id', sa.Integer(), nullable=False),
    sa.Column('edad_dias', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('peso_promedio', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('alimento_consumido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('indice_crecimiento', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('conversion', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('mortandad_pct', sa.Numeric(precision=7, scale=5), nullable=False),
    sa.Column('indice_eficiencia', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['crianza_galpon_id'], ['crianza_galpones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crianza_galpon_id')
    )
    op.create_table('ingresos_aves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crianza_galpon_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('origen', sa.String(length=120), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('muertos_transporte', sa.Integer(), nullable=False),
    sa.Column('cantidad_neta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crianza_galpon_id'], ['crianza_galpones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecturas_diarias_galpon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crianza_galpon_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mortandad', sa.Integer(), nullable=False),
    sa.Column('lectura_agua', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cargado_por_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cargado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['crianza_galpon_id'], ['crianza_galpones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crianza_galpon_id', 'fecha')
    )
    op.create_table('retiros_camion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crianza_galpon_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('remito', sa.String(length=50), nullable=False),
    sa.Column('transportista', sa.String(length=120), nullable=False),
    sa.Column('hora_salida', sa.Time(), nullable=True),
    sa.Column('cantidad_aves', sa.Integer(), nullable=False),
    sa.Column('peso_bruto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('peso_tara', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('peso_neto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cargado_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cargado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['crianza_galpon_id'], ['crianza_galpones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lectura_diaria_galpon_id', sa.Integer(), nullable=True),
    sa.Column('lectura_diaria_granja_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('mortandad', 'agua', 'gas', 'electricidad', name='tipoalerta'), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resuelta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lectura_diaria_galpon_id'], ['lecturas_diarias_galpon.id'], ),
    sa.ForeignKeyConstraint(['lectura_diaria_granja_id'], ['lecturas_diarias_granja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertas')
    op.drop_table('retiros_camion')
    op.drop_table('lecturas_diarias_galpon')
    op.drop_table('ingresos_aves')
    op.drop_table('cierres_galpon')
    op.drop_table('lecturas_diarias_granja')
    op.drop_table('entregas_insumo')
    op.drop_table('crianza_galpones')
    op.drop_table('cierres_crianza')
    op.drop_index(op.f('ix_crianzas_numero'), table_name='crianzas')
    op.drop_table('crianzas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('galpones')
    op.drop_index(op.f('ix_estandares_dia_vida'), table_name='estandares')
    op.drop_table('estandares')
    # ### end Alembic commands ###
